### PR TITLE
Update Nullable annotations in URI.java

### PR DESCRIPTION
**Pull request by mattulbrich**
After a discussion with @wmdietl we decided to amend the annotations in this class.

Perhaps this commit does not catch all cases.

### CODE REVIEW

**Review by wmdietl — APPROVED** [review]
Thanks for these additions!
I made small tweaks in https://github.com/eisop/jdk/pull/48/commits/3f865598b5385b759de770d80f74620c4d68fa2d, please see if you agree.

**Comment by wmdietl** [comment]
@cpovirk Do you have any experience with this class? I see it's not annotated in jspecify/jdk. Would you want a PR?

**Comment by cpovirk** [comment]
Thanks! We have a stub for `URI` inside Google, but I think I found it relatively intimidating to upstream, and then I forgot. Sorry to make you folks have to do it. This matches what we have, and I'd be happy to see the same thing in jspecify/jdk.

**Comment by wmdietl** [comment]
Subsumed by #63. Thanks again for starting this!

**Pull request closed without merging**
